# Generated by Django 2.0.6 on 2018-06-13 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('issue_or_change', models.CharField(max_length=400)),
                ('full_note', models.CharField(max_length=400)),
                ('cid', models.CharField(max_length=25)),
                ('processed_note', models.CharField(max_length=400)),
                ('date_field', models.CharField(max_length=30)),
            ],
        ),
    ]
